# Generated by Django 5.1.5 on 2025-02-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lista', models.CharField(max_length=30)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('fodase', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_entrada', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluido'), ('EP', 'Em progresso')], default='P', max_length=2)),
                ('lista_origem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='base.lista')),
            ],
        ),
    ]
