# Generated by Django 5.1.5 on 2025-02-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='fodase',
        ),
    ]
