# Generated by Django 5.1.5 on 2025-02-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lista_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='lista_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='base.lista'),
        ),
    ]
